import './globals.css'

import React  from 'react';

export const metadata = {
  title: 'مدیریت غلطک ها',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en" dir="rtl">
      <body>
        {children}
      </body>
    </html>
  )
  
}