import './globals.css'

import React  from 'react';

import { Provider } from 'react-redux';
import store from '../store/store';


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  

  return (
    <html lang="en" dir="rtl">
      <body>
        <Provider store={store}>
          
              {children}

        </Provider>
      </body>
    </html>
  )
}